feat: реализация ТЗ 13
necron33rus/java-shareit pull request #1
Opened 2023-07-21 09:35 UTC by necron33rus

реализовал ТЗ №13

2023-07-21 20:04 UTC, Frilock requested changes
Добрый вечер, в целом все ок, но указал ряд комментариев. Жду новую версию

2023-07-21 20:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/CustomExceptionHandler.java
> +        log.error(exception.getMessage());
Предложил бы детализировать лог, например, указывать код произошедшей ошибки

2023-07-21 20:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestBody @Valid ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") long userId) {
Данный литерал X-Sharer-User-Id повторяется более 2х раз - вынесите в константу

2023-07-21 20:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        log.info("POST method: create item");
Детализируйте лог, хотя бы логируйте ид, который в запросе приходит

2023-07-21 20:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (itemDto.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-07-21 20:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                findAllItemDtoByFilter(item -> item.getName().toLowerCase().contains(text.toLowerCase())
Используйте StringUtils.containsIgnoreCase

2023-07-24 12:03 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestBody @Valid ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") long userId) {
done

2023-07-24 13:28 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                findAllItemDtoByFilter(item -> item.getName().toLowerCase().contains(text.toLowerCase())
done

2023-07-24 13:34 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (itemDto.getName() != null) {
done

2023-07-24 13:51 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/exception/CustomExceptionHandler.java
> +        log.error(exception.getMessage());
done

2023-07-24 13:51 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        log.info("POST method: create item");
done

2023-07-24 19:22 UTC, Frilock approved these changes
Добрый вечер, работу принимаю, но есть ряд нюансов где можно упростить код. Обратите внимание пожалуйста

2023-07-24 19:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/CustomExceptionHandler.java
> +        log.error(Arrays.toString(exception.getStackTrace()));
getMessage дополнительно с кодом ошибки было бы информативнее на мой взгляд

2023-07-24 19:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String CUSTOM_USER_ID_HEADER = "X-Sharer-User-Id";
static final поля располагаются выше final полей

2023-07-24 19:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        log.info("ItemController: GET method: get item with id={}", itemId);
По идее ItemController: можно не логгировать, при логгировании вроде класс видно, если не ошибаюсь

2023-07-24 19:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (Optional.ofNullable(itemDto.getName()).isPresent()) {
Имелась ввиду другая конструкция:
Optional.ofNullable(itemDto.getName).ifPreset(updatedItem::setName)

2023-07-24 19:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>              updatedItem.setName(itemDto.getName());
Вообще установите себе плагин sonarlint и на будущее jpa buddy, покажут ряд хороших практик

2023-08-13 18:24 UTC, merged