feat: ТЗ-15
necron33rus/java-shareit pull request #3
Opened 2023-08-31 20:52 UTC by necron33rus

2023-09-01 17:33 UTC, Frilock requested changes
Добрый вечер, комментарии в коде

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +    TEST
А этот статус зачем?

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private static final String CUSTOM_USER_ID_HEADER = "X-Sharer-User-Id";
static final поля располагаются выше final полей

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +@Component
А зачем вам делать маппер бином? Если у него только статические методы

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @NotNull
Дублируется аннотация

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @JsonIgnore
А зачем вам эта аннотация? Вы не хотите отдавать на форму данные в контролере? Но тогда лучше ее использовать в ДТОшке, а это класс по работе с БД

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +
Лишняя пустая строка

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequestDto itemRequestDto, long userId) {
Разве тут транзакция не нужна?

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/utils/EntityUtils.java
> +    public static BookingState parseState(String state) {
А зачем из енама этот метод перенести? Ему наоборот там логичнее находится

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/utils/EntityUtils.java
> +        if (state == null || state.isBlank()) {
можно через StringUtils.isBlank проверять

2023-09-01 17:33 UTC, Frilock commented on src/main/resources/schema.sql
>      description     varchar                                     not null,
В своих скриптах когда создаете таблицы продумывайте размерность полей, и указывайте ее

2023-09-01 17:33 UTC, Frilock commented on src/test/java/ru/practicum/shareit/service/BookingServiceTest.java
> +        var booking1 = Booking.builder()
Вы можете этот повторящийся код вынести в приватный метод

2023-09-01 17:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private List<BookingDto> pagination(int from, int size, List<BookingDto> list) {
Название метода спорное конечно

2023-09-02 07:04 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +    TEST
да для тестов хотел использовать) убрал

2023-09-02 07:05 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private static final String CUSTOM_USER_ID_HEADER = "X-Sharer-User-Id";
done

2023-09-02 07:07 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +@Component
done

2023-09-02 07:07 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @NotNull
done

2023-09-02 07:10 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @JsonIgnore
done

2023-09-02 07:12 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/utils/EntityUtils.java
> +    public static BookingState parseState(String state) {
done

2023-09-02 07:13 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/utils/EntityUtils.java
> +        if (state == null || state.isBlank()) {
done

2023-09-02 07:25 UTC, necron33rus commented on src/main/resources/schema.sql
>      description     varchar                                     not null,
done

2023-09-02 07:47 UTC, necron33rus commented on src/test/java/ru/practicum/shareit/service/BookingServiceTest.java
> +        var booking1 = Booking.builder()
done

2023-09-02 07:50 UTC, necron33rus commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private List<BookingDto> pagination(int from, int size, List<BookingDto> list) {
поменял)

2023-09-02 11:10 UTC, Frilock approved these changes
Принято

2023-09-02 12:10 UTC, merged